import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import { AppLanguage } from "./types";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function formatCredits(credits: number) {
  return new Intl.NumberFormat().format(credits);
}

export function formatDate(timestamp: any) {
  if (!timestamp) return "";
  const date = timestamp.toDate ? timestamp.toDate() : new Date(timestamp);
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }).format(date);
}

const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    voice: "Voice Translate",
    text: "Text Translate",
    calls: "Phone Calls",
    history: "History",
    settings: "Settings",
    admin: "Admin Panel",
    welcome: "Welcome back",
    credits: "Credits",
    logout: "Logout",
    recording: "Recording...",
    ready: "Ready to translate",
    clear: "Clear",
    translate: "Translate",
    source_lang: "Source Language",
    target_lang: "Target Language",
    auto_detect: "Auto Detect",
    theme: "Theme",
    app_lang: "App Language",
    voice_settings: "Translation Voice",
    color_scheme: "Color Scheme",
    save_settings: "Save Settings",
    settings_saved: "Settings saved!",
    insufficient_credits: "Insufficient credits to start a session.",
    live_transcription: "Live Transcription",
    waiting_speech: "Waiting for speech...",
    active_call: "Active Call",
    ready_call: "Ready to Call",
    add_user: "Add User",
    admin_mode: "Administrator Mode",
    total_users: "Total Users",
    total_credits: "Total Credits Circulating",
    voice_sessions: "Voice Sessions",
    text_sessions: "Text Sessions",
    user_management: "User Management",
    credit_adjustment: "Credit Adjustment",
    amount_to_add: "Amount to Add",
    cancel: "Cancel",
    create_profile: "Create Profile",
    search_placeholder: "Search by name or email...",
    recent_activity: "Recent Activity",
    no_history: "No translation history yet.",
    type: "Type",
    languages: "Languages",
    cost: "Cost",
    date: "Date",
    buy_credits: "Buy More Credits",
    contacts: "Contacts",
    new_contact: "New Contact",
    edit_contact: "Edit Contact",
    full_name: "Full Name",
    phone_number: "Phone Number",
    preferred_lang: "Preferred Language",
    photo_url: "Photo URL (Optional)",
    save_contact: "Save Contact",
    search_contacts: "Search contacts...",
    no_contacts: "No contacts found",
    add_first_contact: "Add your first contact",
    quick_access: "Quick Access",
    add_manually: "Add manually",
    update_details: "Update details",
    username: "Username",
    password: "Password",
    finish: "Finish",
    continue: "Continue",
    back: "Back",
    all_set: "All Set!",
    appearance: "Appearance",
    src: "Src",
    dst: "Dst",
    auto: "Auto",
    personalize_experience: "Personalize your translation experience.",
    failed_save_settings: "Failed to save settings. Please try again.",
    failed_save_profile: "Failed to save profile. Please try again.",
    profile_photo_url: "Profile Photo URL",
    display_name: "Display Name",
    your_name: "Your Name",
    email_address: "Email Address",
    gemini_api_key: "Gemini API Key",
    required_real_translation: "Required for Real Translation",
    get_key_from: "Get your key from",
    key_stored_locally: "Key is stored locally in your browser.",
    save_profile: "Save Profile",
    saving_changes: "Saving changes...",
    something_went_wrong: "Something went wrong.",
    no_permission: "You don't have permission to perform this action. Please check your account status.",
    application_error: "Application Error",
    reload_application: "Reload Application",
    breaking_barriers: "Breaking barriers, one word at a time.",
    continue_google: "Continue with Google",
    google_offline: "Google Login Offline",
    or_email_login: "Or email login",
    email: "Email",
    login: "Login",
    no_account: "Don't have an account?",
    register_now: "Register Now",
    phone: "Phone",
    location: "Location",
    create_account: "Create Account",
    back_to_login: "Back to Login",
    terms_privacy: "By continuing, you agree to our Terms of Service and Privacy Policy.",
    manage_partners: "Manage your translation partners",
    offline: "Offline",
    review_history: "Review your past translations and credit usage.",
    search_history: "Search history...",
    all: "All",
    voice_session: "Voice Session",
    text_session: "Text Session",
    call_session: "Call Session",
    usage: "Usage",
    no_transactions: "No transactions found.",
    no_history_category: "No history found for this category.",
    source: "Source",
    translation: "Translation",
    audio_input: "Audio input",
    audio_output: "Audio output",
  },
  sr: {
    dashboard: "Kontrolna tabla",
    voice: "Glasovni prevod",
    text: "Tekstualni prevod",
    calls: "Telefonski pozivi",
    history: "Istorija",
    settings: "Podešavanja",
    admin: "Admin panel",
    welcome: "Dobrodošli nazad",
    credits: "Krediti",
    logout: "Odjavi se",
    recording: "Snimanje...",
    ready: "Spreman za prevod",
    clear: "Obriši",
    translate: "Prevedi",
    source_lang: "Izvorni jezik",
    target_lang: "Ciljni jezik",
    auto_detect: "Automatska detekcija",
    theme: "Tema",
    app_lang: "Jezik aplikacije",
    voice_settings: "Glas prevoda",
    color_scheme: "Šema boja",
    save_settings: "Sačuvaj podešavanja",
    settings_saved: "Podešavanja sačuvana!",
    insufficient_credits: "Nedovoljno kredita za početak sesije.",
    live_transcription: "Transkripcija uživo",
    waiting_speech: "Čekanje na govor...",
    active_call: "Aktivan poziv",
    ready_call: "Spreman za poziv",
    add_user: "Dodaj korisnika",
    admin_mode: "Administratorski režim",
    total_users: "Ukupno korisnika",
    total_credits: "Ukupno kredita u opticaju",
    voice_sessions: "Glasovne sesije",
    text_sessions: "Tekstualne sesije",
    user_management: "Upravljanje korisnicima",
    credit_adjustment: "Podešavanje kredita",
    amount_to_add: "Iznos za dodavanje",
    cancel: "Otkaži",
    create_profile: "Kreiraj profil",
    search_placeholder: "Pretraži po imenu ili mejlu...",
    recent_activity: "Nedavna aktivnost",
    no_history: "Još uvek nema istorije prevoda.",
    type: "Tip",
    languages: "Jezici",
    cost: "Cena",
    date: "Datum",
    buy_credits: "Kupi još kredita",
    contacts: "Kontakti",
    new_contact: "Novi kontakt",
    edit_contact: "Izmeni kontakt",
    full_name: "Puno ime",
    phone_number: "Broj telefona",
    preferred_lang: "Željeni jezik",
    photo_url: "URL fotografije (opciono)",
    save_contact: "Sačuvaj kontakt",
    search_contacts: "Pretraži kontakte...",
    no_contacts: "Nema pronađenih kontakata",
    add_first_contact: "Dodaj svoj prvi kontakt",
    quick_access: "Brzi pristup",
    add_manually: "Dodaj ručno",
    update_details: "Ažuriraj detalje",
    username: "Korisničko ime",
    password: "Lozinka",
    finish: "Završi",
    continue: "Nastavi",
    back: "Nazad",
    all_set: "Sve je spremno!",
    appearance: "Izgled",
    src: "Izv",
    dst: "Cilj",
    auto: "Auto",
    personalize_experience: "Personalizujte svoje iskustvo prevoda.",
    failed_save_settings: "Greška pri čuvanju podešavanja. Pokušajte ponovo.",
    failed_save_profile: "Greška pri čuvanju profila. Pokušajte ponovo.",
    profile_photo_url: "URL profilne fotografije",
    display_name: "Ime za prikaz",
    your_name: "Vaše ime",
    email_address: "Email adresa",
    gemini_api_key: "Gemini API ključ",
    required_real_translation: "Obavezno za pravi prevod",
    get_key_from: "Preuzmite ključ sa",
    key_stored_locally: "Ključ se čuva lokalno u vašem pretraživaču.",
    save_profile: "Sačuvaj profil",
    saving_changes: "Čuvanje promena...",
    something_went_wrong: "Nešto je pošlo naopako.",
    no_permission: "Nemate dozvolu za ovu radnju. Proverite status naloga.",
    application_error: "Greška u aplikaciji",
    reload_application: "Ponovo učitaj aplikaciju",
    breaking_barriers: "Rušimo barijere, reč po reč.",
    continue_google: "Nastavi sa Google-om",
    google_offline: "Google prijava nije dostupna (Offline)",
    or_email_login: "Ili prijava putem email-a",
    email: "Email",
    login: "Prijavi se",
    no_account: "Nemate nalog?",
    register_now: "Registrujte se sada",
    phone: "Telefon",
    location: "Lokacija",
    create_account: "Kreiraj nalog",
    back_to_login: "Nazad na prijavu",
    terms_privacy: "Nastavkom se slažete sa našim Uslovima korišćenja i Politikom privatnosti.",
    manage_partners: "Upravljajte svojim partnerima za prevod",
    offline: "Van mreže",
    review_history: "Pregledajte svoje prošle prevode i korišćenje kredita.",
    search_history: "Pretraži istoriju...",
    all: "Sve",
    voice_session: "Glasovna sesija",
    text_session: "Tekstualna sesija",
    call_session: "Telefonska sesija",
    usage: "Upotreba",
    no_transactions: "Nema pronađenih transakcija.",
    no_history_category: "Nema istorije za ovu kategoriju.",
    source: "Izvor",
    translation: "Prevod",
    audio_input: "Audio ulaz",
    audio_output: "Audio izlaz",
  },
  hu: {
    dashboard: "Irányítópult",
    voice: "Hangfordítás",
    text: "Szövegfordítás",
    calls: "Telefonhívások",
    history: "Előzmények",
    settings: "Beállítások",
    admin: "Adminisztrációs panel",
    welcome: "Üdvözöljük újra",
    credits: "Kreditek",
    logout: "Kijelentkezés",
    recording: "Felvétel...",
    ready: "Fordításra kész",
    clear: "Törlés",
    translate: "Fordítás",
    source_lang: "Forrásnyelv",
    target_lang: "Célnyelv",
    auto_detect: "Automatikus felismerés",
    theme: "Téma",
    app_lang: "Alkalmazás nyelve",
    voice_settings: "Fordítás hangja",
    color_scheme: "Színséma",
    save_settings: "Beállítások mentése",
    settings_saved: "Beállítások mentve!",
    insufficient_credits: "Nincs elég kredit a munkamenet indításához.",
    live_transcription: "Élő átirat",
    waiting_speech: "Várakozás beszédre...",
    active_call: "Aktív hívás",
    ready_call: "Hívásra kész",
    add_user: "Felhasználó hozzáadása",
    admin_mode: "Adminisztrátori mód",
    total_users: "Összes felhasználó",
    total_credits: "Összes forgalomban lévő kredit",
    voice_sessions: "Hangmunkamenetek",
    text_sessions: "Szöveges munkamenetek",
    user_management: "Felhasználókezelés",
    credit_adjustment: "Kredit módosítása",
    amount_to_add: "Hozzáadandó összeg",
    cancel: "Mégse",
    create_profile: "Profil létrehozása",
    search_placeholder: "Keresés név vagy e-mail alapján...",
    recent_activity: "Legutóbbi tevékenység",
    no_history: "Még nincs fordítási előzmény.",
    type: "Típus",
    languages: "Nyelvek",
    cost: "Költség",
    date: "Dátum",
    buy_credits: "Vásároljon több kreditet",
    contacts: "Kapcsolatok",
    new_contact: "Új kapcsolat",
    edit_contact: "Kapcsolat szerkesztése",
    full_name: "Teljes név",
    phone_number: "Telefonszám",
    preferred_lang: "Preferált nyelv",
    photo_url: "Fotó URL (opcionális)",
    save_contact: "Kapcsolat mentése",
    search_contacts: "Kapcsolatok keresése...",
    no_contacts: "Nem találhatók kapcsolatok",
    add_first_contact: "Adja hozzá első kapcsolatát",
    quick_access: "Gyors elérés",
    add_manually: "Hozzáadás manuálisan",
    update_details: "Részletek frissítése",
    username: "Felhasználónév",
    password: "Jelszó",
    finish: "Befejezés",
    continue: "Folytatás",
    back: "Vissza",
    all_set: "Minden kész!",
    appearance: "Megjelenés",
    src: "Forr",
    dst: "Cél",
    auto: "Auto",
    personalize_experience: "Személyre szabhatja fordítási élményét.",
    failed_save_settings: "Nem sikerült menteni a beállításokat. Próbálja újra.",
    failed_save_profile: "Nem sikerült menteni a profilt. Próbálja újra.",
    profile_photo_url: "Profilkép URL",
    display_name: "Megjelenített név",
    your_name: "Az Ön neve",
    email_address: "E-mail cím",
    gemini_api_key: "Gemini API kulcs",
    required_real_translation: "Szükséges a valódi fordításhoz",
    get_key_from: "Szerezze be kulcsát innen:",
    key_stored_locally: "A kulcs helyileg tárolódik a böngészőben.",
    save_profile: "Profil mentése",
    saving_changes: "Módosítások mentése...",
    something_went_wrong: "Valami elromlott.",
    no_permission: "Nincs jogosultsága ehhez a művelethez. Ellenőrizze fiókja állapotát.",
    application_error: "Alkalmazás hiba",
    reload_application: "Alkalmazás újratöltése",
    breaking_barriers: "Lebontjuk a korlátokat, szóról szóra.",
    continue_google: "Folytatás Google-lal",
    google_offline: "Google bejelentkezés offline",
    or_email_login: "Vagy e-mail bejelentkezés",
    email: "E-mail",
    login: "Bejelentkezés",
    no_account: "Nincs még fiókja?",
    register_now: "Regisztráljon most",
    phone: "Telefon",
    location: "Helyszín",
    create_account: "Fiók létrehozása",
    back_to_login: "Vissza a bejelentkezéshez",
    terms_privacy: "A folytatással elfogadja a Felhasználási feltételeket és az Adatvédelmi szabályzatot.",
    manage_partners: "Kezelje fordítási partnereit",
    offline: "Offline",
    review_history: "Tekintse át korábbi fordításait és kreditfelhasználását.",
    search_history: "Keresés az előzményekben...",
    all: "Összes",
    voice_session: "Hangalapú munkamenet",
    text_session: "Szöveges munkamenet",
    call_session: "Hívás munkamenet",
    usage: "Használat",
    no_transactions: "Nem találhatók tranzakciók.",
    no_history_category: "Nincs előzmény ebben a kategóriában.",
    source: "Forrás",
    translation: "Fordítás",
    audio_input: "Audio bemenet",
    audio_output: "Audio kimenet",
  },
  de: {
    dashboard: "Dashboard",
    voice: "Sprachübersetzung",
    text: "Textübersetzung",
    calls: "Telefonanrufe",
    history: "Verlauf",
    settings: "Einstellungen",
    admin: "Admin-Panel",
    welcome: "Willkommen zurück",
    credits: "Credits",
    logout: "Abmelden",
    recording: "Aufnahme...",
    ready: "Bereit zum Übersetzen",
    clear: "Löschen",
    translate: "Übersetzen",
    source_lang: "Quellsprache",
    target_lang: "Zielsprache",
    auto_detect: "Automatische Erkennung",
    theme: "Thema",
    app_lang: "App-Sprache",
    voice_settings: "Übersetzungsstimme",
    color_scheme: "Farbschema",
    save_settings: "Einstellungen speichern",
    settings_saved: "Einstellungen gespeichert!",
    insufficient_credits: "Nicht genügend Credits für eine Sitzung.",
    live_transcription: "Live-Transkription",
    waiting_speech: "Warten auf Sprache...",
    active_call: "Aktiver Anruf",
    ready_call: "Bereit zum Anrufen",
    add_user: "Benutzer hinzufügen",
    admin_mode: "Administratormodus",
    total_users: "Benutzer insgesamt",
    total_credits: "Credits im Umlauf",
    voice_sessions: "Sprachsitzungen",
    text_sessions: "Text-Sitzungen",
    user_management: "Benutzerverwaltung",
    credit_adjustment: "Kreditanpassung",
    amount_to_add: "Hinzuzufügender Betrag",
    cancel: "Abbrechen",
    create_profile: "Profil erstellen",
    search_placeholder: "Suche nach Name oder E-Mail...",
    recent_activity: "Letzte Aktivität",
    no_history: "Noch kein Übersetzungsverlauf.",
    type: "Typ",
    languages: "Sprachen",
    cost: "Kosten",
    date: "Datum",
    buy_credits: "Mehr Credits kaufen",
    contacts: "Kontakte",
    new_contact: "Neuer Kontakt",
    edit_contact: "Kontakt bearbeiten",
    full_name: "Vollständiger Name",
    phone_number: "Telefonnummer",
    preferred_lang: "Bevorzugte Sprache",
    photo_url: "Foto-URL (optional)",
    save_contact: "Kontakt speichern",
    search_contacts: "Kontakte suchen...",
    no_contacts: "Keine Kontakte gefunden",
    add_first_contact: "Fügen Sie Ihren ersten Kontakt hinzu",
    quick_access: "Schnellzugriff",
    add_manually: "Manuell hinzufügen",
    update_details: "Details aktualisieren",
    username: "Benutzername",
    password: "Passwort",
    finish: "Fertigstellen",
    continue: "Weiter",
    back: "Zurück",
    all_set: "Alles bereit!",
    appearance: "Aussehen",
    src: "Quell",
    dst: "Ziel",
    auto: "Auto",
    personalize_experience: "Personalisieren Sie Ihr Übersetzungserlebnis.",
    failed_save_settings: "Einstellungen konnten nicht gespeichert werden. Bitte versuchen Sie es erneut.",
    failed_save_profile: "Profil konnte nicht gespeichert werden. Bitte versuchen Sie es erneut.",
    profile_photo_url: "Profilfoto-URL",
    display_name: "Anzeigename",
    your_name: "Ihr Name",
    email_address: "E-Mail-Adresse",
    gemini_api_key: "Gemini API-Schlüssel",
    required_real_translation: "Erforderlich für echte Übersetzung",
    get_key_from: "Holen Sie sich Ihren Schlüssel von",
    key_stored_locally: "Der Schlüssel wird lokal in Ihrem Browser gespeichert.",
    save_profile: "Profil speichern",
    saving_changes: "Änderungen werden gespeichert...",
    something_went_wrong: "Etwas ist schief gelaufen.",
    no_permission: "Sie haben keine Berechtigung für diese Aktion. Bitte überprüfen Sie Ihren Kontostatus.",
    application_error: "Anwendungsfehler",
    reload_application: "Anwendung neu laden",
    breaking_barriers: "Barrieren abbauen, Wort für Wort.",
    continue_google: "Mit Google fortfahren",
    google_offline: "Google-Login offline",
    or_email_login: "Oder E-Mail-Login",
    email: "E-Mail",
    login: "Anmelden",
    no_account: "Haben Sie noch kein Konto?",
    register_now: "Jetzt registrieren",
    phone: "Telefon",
    location: "Standort",
    create_account: "Konto erstellen",
    back_to_login: "Zurück zum Login",
    terms_privacy: "Durch Fortfahren stimmen Sie unseren Nutzungsbedingungen und Datenschutzbestimmungen zu.",
    manage_partners: "Verwalten Sie Ihre Übersetzungspartner",
    offline: "Offline",
    review_history: "Überprüfen Sie Ihre vergangenen Übersetzungen und die Guthabennutzung.",
    search_history: "Verlauf durchsuchen...",
    all: "Alle",
    voice_session: "Sprachsitzung",
    text_session: "Textsitzung",
    call_session: "Anrufsitzung",
    usage: "Nutzung",
    no_transactions: "Keine Transaktionen gefunden.",
    no_history_category: "Kein Verlauf für diese Kategorie gefunden.",
    source: "Quelle",
    translation: "Übersetzung",
    audio_input: "Audio-Eingang",
    audio_output: "Audio-Ausgang",
  },
  sl: {
    dashboard: "Nadzorna plošča",
    voice: "Glasovno prevajanje",
    text: "Besedilno prevajanje",
    calls: "Telefonski klici",
    history: "Zgodovina",
    settings: "Nastavitve",
    admin: "Admin plošča",
    welcome: "Dobrodošli nazaj",
    credits: "Krediti",
    logout: "Odjava",
    recording: "Snemanje...",
    ready: "Pripravljen na prevod",
    clear: "Počisti",
    translate: "Prevedi",
    source_lang: "Izvorni jezik",
    target_lang: "Ciljni jezik",
    auto_detect: "Samodejno zaznavanje",
    theme: "Tema",
    app_lang: "Jezik aplikacije",
    voice_settings: "Glas prevoda",
    color_scheme: "Barvna shema",
    save_settings: "Shrani nastavitve",
    settings_saved: "Nastavitve shranjene!",
    insufficient_credits: "Premalo kreditov za začetek seje.",
    live_transcription: "Transkripcija v živo",
    waiting_speech: "Čakanje na govor...",
    active_call: "Aktiven klic",
    ready_call: "Pripravljen na klic",
    add_user: "Dodaj uporabnika",
    admin_mode: "Administratorski način",
    total_users: "Skupaj uporabnikov",
    total_credits: "Skupaj kreditov v obtoku",
    voice_sessions: "Glasovne seje",
    text_sessions: "Besedilne seje",
    user_management: "Upravljanje uporabnikov",
    credit_adjustment: "Prilagoditev kreditov",
    amount_to_add: "Znesek za dodajanje",
    cancel: "Prekliči",
    create_profile: "Ustvari profil",
    search_placeholder: "Išči po imenu ali e-pošti...",
    recent_activity: "Nedavna dejavnost",
    no_history: "Še ni zgodovine prevodov.",
    type: "Vrsta",
    languages: "Jeziki",
    cost: "Strošek",
    date: "Datum",
    buy_credits: "Kupi več kreditov",
    contacts: "Stiki",
    new_contact: "Nov stik",
    edit_contact: "Uredi stik",
    full_name: "Polno ime",
    phone_number: "Telefonska številka",
    preferred_lang: "Prednostni jezik",
    photo_url: "URL fotografije (neobvezno)",
    save_contact: "Shrani stik",
    search_contacts: "Išči stike...",
    no_contacts: "Ni najdenih stikov",
    add_first_contact: "Dodaj svoj prvi stik",
    quick_access: "Hitri dostop",
    add_manually: "Dodaj ročno",
    update_details: "Posodobi podrobnosti",
    username: "Uporabniško ime",
    password: "Geslo",
    finish: "Končaj",
    continue: "Nadaljuj",
    back: "Nazaj",
    all_set: "Vse je pripravljeno!",
    appearance: "Videz",
    src: "Vir",
    dst: "Cilj",
    auto: "Samod",
    personalize_experience: "Prilagodite svojo izkušnjo prevajanja.",
    failed_save_settings: "Nastavitev ni bilo mogoče shraniti. Poskusite znova.",
    failed_save_profile: "Profila ni bilo mogoče shraniti. Poskusite znova.",
    profile_photo_url: "URL profilne fotografije",
    display_name: "Prikazno ime",
    your_name: "Vaše ime",
    email_address: "E-poštni naslov",
    gemini_api_key: "Gemini API ključ",
    required_real_translation: "Obvezno za pravi prevod",
    get_key_from: "Pridobite ključ na",
    key_stored_locally: "Ključ je shranjen lokalno v vašem brskalniku.",
    save_profile: "Shrani profil",
    saving_changes: "Shranjevanje sprememb...",
    something_went_wrong: "Nekaj je šlo narobe.",
    no_permission: "Nimate dovoljenja za to dejanje. Preverite status računa.",
    application_error: "Napaka aplikacije",
    reload_application: "Ponovno naloži aplikacijo",
    breaking_barriers: "Podiranje ovir, besedo za besedo.",
    continue_google: "Nadaljuj z Googlom",
    google_offline: "Google prijava ni na voljo (brez povezave)",
    or_email_login: "Ali prijava z e-pošto",
    email: "E-pošta",
    login: "Prijava",
    no_account: "Nimate računa?",
    register_now: "Registrirajte se zdaj",
    phone: "Telefon",
    location: "Lokacija",
    create_account: "Ustvari račun",
    back_to_login: "Nazad na prijavu",
    terms_privacy: "Z nadaljevanjem se strinjate z našimi pogoji storitve in politiko zasebnosti.",
    manage_partners: "Upravljajte svoje partnerje za prevajanje",
    offline: "Brez povezave",
    review_history: "Preglejte svoje pretekle prevode in porabo kreditov.",
    search_history: "Išči po zgodovini...",
    all: "Vse",
    voice_session: "Glasovna seja",
    text_session: "Besedilna seja",
    call_session: "Telefonska seja",
    usage: "Poraba",
    no_transactions: "Ni najdenih transakcij.",
    no_history_category: "V tej kategoriji ni zgodovine.",
    source: "Vir",
    translation: "Prevod",
    audio_input: "Avdio vhod",
    audio_output: "Avdio izhod",
  },
};

export function t(key: string, lang: AppLanguage = "en") {
  return TRANSLATIONS[lang]?.[key] || key;
}
